# Generated by Django 2.1.9 on 2019-06-24 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('socialaccount', '0003_extra_data_default_dict'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialUserProfile',
            fields=[
                ('social_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to='socialaccount.SocialAccount')),
                ('is_active', models.BooleanField(default=True)),
                ('profile_picture', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
